import type { Project } from "@/types";

export const projects: Project[] = [
  {
    slug: "quant-terminal",
    name: "Quant Terminal",
    tagline: "A personal trading dashboard and research environment.",
    description:
      "A self-hosted terminal that unifies market data, strategy signals, and portfolio state into one live view.",
    longDescription:
      "Quant Terminal is the cockpit for daily research: streaming price data, custom indicator panels, and a signal feed generated by strategies running in Strategy Lab. Built to replace a scattered stack of spreadsheets and browser tabs with a single, fast, keyboard-driven interface.",
    technologies: ["Python", "FastAPI", "PostgreSQL", "React", "WebSockets"],
    status: "In Development",
    achievements: [
      "Sub-100ms tick-to-render latency on live price feeds",
      "Unified 6 previously separate research spreadsheets into one workspace",
      "Custom charting layer built without third-party charting libraries",
    ],
    githubUrl: "https://github.com/johndoe/quant-terminal",
    demoUrl: "https://team-chain-v2.vercel.app",
    accent: "ice",
    featured: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/John_Doe%2C_born_John_Nommensen_Duchac.jpg/960px-John_Doe%2C_born_John_Nommensen_Duchac.jpg",
  },
  {
    slug: "onchain-scanner",
    name: "On-chain Scanner",
    tagline: "A wallet intelligence and blockchain analytics platform.",
    description:
      "Traces wallet clusters, labels behavior patterns, and surfaces early signals from on-chain activity.",
    longDescription:
      "On-chain Scanner ingests raw chain data, clusters related wallets using heuristic and graph-based methods, and scores addresses for behaviors like accumulation, distribution, and bridging activity. Designed as a research tool first, not a product — every heuristic is inspectable and versioned.",
    technologies: ["Rust", "Solidity", "The Graph", "ClickHouse", "Next.js"],
    status: "Live",
    achievements: [
      "Indexes 4 EVM chains with under 2-block lag",
      "Wallet clustering heuristics validated against 3 known entity datasets",
      "Powers the wallet-tagging layer used inside Quant Terminal",
    ],
    githubUrl: "https://github.com/johndoe/onchain-scanner",
    demoUrl: "https://demo.johndoe.dev/onchain-scanner",
    accent: "amber",
    featured: true,
  },
  {
    slug: "strategy-lab",
    name: "Strategy Lab",
    tagline: "A research framework for testing algorithmic trading strategies.",
    description:
      "An event-driven backtesting engine built to make strategy iteration fast and statistically honest.",
    longDescription:
      "Strategy Lab enforces a strict separation between signal, execution, and risk logic, so backtests are harder to accidentally overfit. It includes walk-forward validation, transaction cost modeling, and a strategy registry so every experiment is reproducible from a single config file.",
    technologies: ["Python", "NumPy", "Pandas", "Backtrader", "Docker"],
    status: "Live",
    achievements: [
      "Backtests 5 years of tick data for a single strategy in under 40 seconds",
      "Built-in walk-forward validation to reduce overfitting risk",
      "37 strategies tested; 4 promoted to paper trading",
    ],
    githubUrl: "https://github.com/johndoe/strategy-lab",
    accent: "ice",
    featured: true,
  },
  {
    slug: "knowledge-graph",
    name: "Knowledge Graph",
    tagline: "A system that connects notes, ideas, books, and concepts into an interactive graph.",
    description:
      "Turns years of scattered notes into a navigable network of linked ideas.",
    longDescription:
      "Knowledge Graph parses journal entries and reading notes for concept mentions, then builds a weighted graph of how ideas across finance, systems thinking, and philosophy actually connect in practice — not just in theory. Powers the Knowledge Map section of this site.",
    technologies: ["TypeScript", "Next.js", "Neo4j", "D3"],
    status: "In Development",
    achievements: [
      "Extracted over 600 concept links from 174 public notes",
      "Custom force-directed layout tuned for readability over raw physical accuracy",
      "Directly powers this website's Knowledge Map",
    ],
    githubUrl: "https://github.com/johndoe/knowledge-graph",
    accent: "amber",
    featured: true,
  },
  {
    slug: "personal-research-os",
    name: "Personal Research OS",
    tagline: "A second-brain system for collecting and organizing knowledge.",
    description:
      "The backbone that captures, tags, and resurfaces everything worth remembering.",
    longDescription:
      "Personal Research OS is the ingestion layer beneath everything else: a capture pipeline for highlights, notes, and fleeting thoughts, normalized into a single searchable store with spaced re-surfacing so old ideas resurface when they become relevant again.",
    technologies: ["TypeScript", "PostgreSQL", "Notion API", "pgvector"],
    status: "Research",
    achievements: [
      "Unified 4 separate note-taking tools into one capture pipeline",
      "Semantic search over 174 notes using local embeddings",
      "Feeds both the Journal and Knowledge Graph sections of this site",
    ],
    githubUrl: "https://github.com/johndoe/personal-research-os",
    accent: "ice",
    featured: true,
  },
];
