import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "next-themes"
import NextSnowScreen from "../components/snow/NextSnowScreen"
import Footer from "@/components/Footer/footer"
import Header from "@/components/Header"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} min-h-screen`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          
          {/* WRAPPER */}
         <div className="flex flex-col min-h-screen">

  <Header />

  {/* Snow overlay (visual only) */}
  <div className="fixed inset-0 pointer-events-none z-10">
    <NextSnowScreen />
  </div>

  <main className="relative z-20 flex-grow">
    {children}
  </main>

</div>

<Footer />

        </ThemeProvider>
      </body>
    </html>
  )
}
